import translate from "./translate"
import deepseekv1 from "./deepseek-coder-67b"
import jawdalSholat from "./jadwal-sholat"
import negro from "./negro"
import anoboy from "./anoboy"
import aio from "./aio"
import text2img from "./text2img"
import aiFluxFast from "./aiFluxFast"
import downloadCapCut from "./capcut"
import randomAnimeQuote from "./quotesAnime"

import * as sakuranovel from "./sakuranovel"
import * as bstation from "./bstation"
import * as Tiktok from "./tiktok"
import * as AniList from "./aniList"
import * as Github from "./github"
import * as Pin from "./pinterest"
import * as Animexin from "./Animexin"
import * as ytdl from "./youtube"

export { translate, deepseekv1, jawdalSholat, negro, anoboy, aio, text2img, aiFluxFast, downloadCapCut, randomAnimeQuote, sakuranovel, bstation, Tiktok, AniList, Github, Pin, Animexin, ytdl }
